# Generated by Django 4.2.5 on 2023-11-23 12:22

import Product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('PID', models.CharField(default=Product.models.Mobile.format, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Brand', models.CharField(max_length=10)),
                ('PName', models.CharField(max_length=12)),
                ('PImage', models.ImageField(upload_to='Mobile')),
                ('Description', models.TextField()),
                ('Price', models.PositiveBigIntegerField()),
                ('Quantity', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('PID',),
            },
        ),
    ]
