# Generated by Django 4.2.5 on 2023-11-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headphone',
            name='PImage',
            field=models.ImageField(null=True, upload_to='HeadPhone', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='PImage',
            field=models.ImageField(null=True, upload_to='Laptop', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='men',
            name='PImage',
            field=models.ImageField(null=True, upload_to='Men', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='PImage',
            field=models.ImageField(null=True, upload_to='Shoe', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='women',
            name='PImage',
            field=models.ImageField(null=True, upload_to='Women', verbose_name='Product Image'),
        ),
    ]
