# Generated by Django 5.0.1 on 2024-02-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headphone',
            name='Category',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='Category',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='men',
            name='Category',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='Category',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='Category',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='women',
            name='Category',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
