# Generated by Django 4.2.5 on 2023-11-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_headphone_pimage_alter_laptop_pimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headphone',
            name='Brand',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='headphone',
            name='PName',
            field=models.CharField(max_length=20, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='Brand',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='PName',
            field=models.CharField(max_length=20, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='men',
            name='Brand',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='men',
            name='PName',
            field=models.CharField(max_length=20, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='Brand',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='PName',
            field=models.CharField(max_length=20, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='Brand',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='PName',
            field=models.CharField(max_length=20, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='women',
            name='Brand',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='women',
            name='PName',
            field=models.CharField(max_length=20, null=True, verbose_name='Product Name'),
        ),
    ]
