# Generated by Django 4.2.5 on 2023-11-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='Name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='Phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='Pincode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='Road_name',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='State',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='house_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
