# Generated by Django 4.2.5 on 2023-10-16 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_address',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Name', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=15)),
                ('Pincode', models.CharField(max_length=6)),
                ('State', models.CharField(max_length=10)),
                ('house_no', models.CharField(max_length=25)),
                ('Road_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=30, verbose_name='name'),
        ),
    ]
