# Generated by Django 4.2.5 on 2023-11-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Account', '0002_alter_user_address_name_alter_user_address_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='Name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='Phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='Pincode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='Road_name',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='State',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='house_no',
            field=models.CharField(max_length=50),
        ),
    ]
