# Generated by Django 4.2.5 on 2023-11-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Account', '0002_user_address_alter_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='Road_name',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='house_no',
            field=models.CharField(max_length=50),
        ),
    ]
