# Generated by Django 4.2.5 on 2023-12-12 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_Account', '0003_alter_user_address_name_alter_user_address_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=15, null=True)),
                ('PName', models.CharField(max_length=20, null=True, verbose_name='Product Name')),
                ('Price', models.PositiveBigIntegerField(null=True)),
                ('Quantity', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
