# Generated by Django 4.2.5 on 2023-12-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Account', '0004_user_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_cart',
            name='PID',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
