# Generated by Django 4.2.5 on 2023-12-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Account', '0005_user_cart_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_cart',
            name='Categories',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
