# Generated by Django 4.2.5 on 2023-12-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Account', '0006_user_cart_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_cart',
            old_name='Categories',
            new_name='Category',
        ),
    ]
