# Generated by Django 4.2.5 on 2023-12-12 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_Account', '0008_user_cart_pimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_time', models.DateTimeField()),
                ('PID', models.CharField(max_length=5, null=True)),
                ('Category', models.CharField(max_length=15, null=True)),
                ('Brand', models.CharField(max_length=15, null=True)),
                ('PName', models.CharField(max_length=20, null=True, verbose_name='Product Name')),
                ('Price', models.PositiveBigIntegerField(null=True)),
                ('Quantity', models.IntegerField(null=True)),
                ('PImage', models.ImageField(null=True, upload_to='', verbose_name='Product Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='cart',
        ),
    ]
