# Generated by Django 5.0.1 on 2024-01-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Account', '0009_order_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Order_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
