# Generated by Django 5.0.1 on 2024-02-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Account', '0012_alter_cart_pid'),
    ]

    operations = [
      
        migrations.DeleteModel(
            name='Order',
        ),
        
    ]
