# Generated by Django 5.0.1 on 2024-02-10 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Account', '0013_remove_user_cart_user_delete_order_delete_user_cart'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_time', models.DateTimeField(auto_now_add=True)),
                ('PID', models.CharField(max_length=10)),
                ('Quantity', models.PositiveIntegerField(default=1)),
                ('Category', models.CharField(max_length=15, null=True)),
                ('Price', models.PositiveBigIntegerField(null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        
    ]
